// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuxqkjg-KmbHreyXBxjo4NjPMRWO6O_VM',
    appId: '1:606892224370:web:53d8691b72bc169ae277eb',
    messagingSenderId: '606892224370',
    projectId: 'fltr-cht-ex',
    authDomain: 'fltr-cht-ex.firebaseapp.com',
    storageBucket: 'fltr-cht-ex.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvIBQbNAoQcN3z_LjSRhNvwEl0nnE4iQ',
    appId: '1:606892224370:android:544caf0372c4adf0e277eb',
    messagingSenderId: '606892224370',
    projectId: 'fltr-cht-ex',
    storageBucket: 'fltr-cht-ex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_q6lk_wi91EJlit1e4o3ou059O0FoXIk',
    appId: '1:606892224370:ios:a68cecf29aff176de277eb',
    messagingSenderId: '606892224370',
    projectId: 'fltr-cht-ex',
    storageBucket: 'fltr-cht-ex.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
